// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJbspm5LHcU6Jy1lbfvJtASDC56laknyQ',
    appId: '1:1079738843768:web:906c0a21e4326ff847a38d',
    messagingSenderId: '1079738843768',
    projectId: 'dropgo-fa413',
    authDomain: 'dropgo-fa413.firebaseapp.com',
    storageBucket: 'dropgo-fa413.firebasestorage.app',
    measurementId: 'G-P8K7R03XZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCGORIVlF5LuhJ2mSS4SSh-xSGvZNyLBs',
    appId: '1:1079738843768:android:20c589360d1ccbb247a38d',
    messagingSenderId: '1079738843768',
    projectId: 'dropgo-fa413',
    storageBucket: 'dropgo-fa413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYc-ddNN0XDSDkWa6960zTaK-5fJs0PQ',
    appId: '1:1079738843768:ios:635f3aad781ce00147a38d',
    messagingSenderId: '1079738843768',
    projectId: 'dropgo-fa413',
    storageBucket: 'dropgo-fa413.firebasestorage.app',
    iosBundleId: 'com.dropgo.app',
  );
}
